### PR TITLE
enhance - docs/build : working on the builder missing info

### PR DESCRIPTION
**Pull request by rbalet**
I wanted to make some change on the builder.  
Tried as said in the [Working on the builder](https://labjs.readthedocs.io/en/latest/meta/contribute/build.html#working-on-the-builder) with but had an error on running `yarn start`.   
It was written that some file was missing under `../library/dist/something.starterkit.js`.  
Since dist is only create when running a build, I thought it may be useful to add it into the doc.

I pushed this one #60. I've only done for the preview button, since Ctrl+s make, for most of the user, sense. 

And also added the prettierrc conf file. (I let you change the value if you aren't agree with his configuration) (Still have to add a linter, but will open another issue for that and after, if you are agree with, we could run the linter and have one big push with everything formated)

### CODE REVIEW

**Comment by FelixHenninger** [comment]
Hi @rbalet , and may thanks for your PR! I've gone through your changes, and separated the PR into its the three contributions. Thanks a lot for the addition to the docs, and the `.prettierrc`! Both are now merged (some minor changes are added, mostly to keep the commit messages in line with our usual format).

As for the shortcut tooltip, I'm personally not so sure regarding the UI, and I would like to ask you whether you could revisit it. Here's a couple of thoughts I had upon reviewing it:

* I'm not sure about a tooltip that shows _only_ the shortcut -- do you think it might be possible to add some more information?
* The shortcut is currently shown as `Ctrl+Alt+P`. That kinda-works on Windows, but on Mac OS (at least on the computers I've tested), the added `alt` triggers the print dialogue, and `ctrl` doesn't work at all. I would kindly ask you to revise this. (similarly, Macs don't use the `+` notation, but that's not something I would be picky about)
* When we figure out a good way of showing the shortcuts, I do think it would be useful to apply that to the save dialogue too, and possibly add a shortcut for opening files too.

Ok, so much for now -- thanks again for your PR, and please let me know if there's anything I can support you with!

Best, -Felix

**Comment by rbalet** [comment]
@FelixHenninger I give you right about the shortcut problem. Didn't thought that far when I implemented it. 
I keep somewhere in my mind and write here if I find something.

**Comment by FelixHenninger** [comment]
Yes, please do! I would be psyched to discuss it too -- I think there must be a solution really close that builds on the code you've already written. If you have a moment next week, would you be open to chatting for 20mins or so and figuring this out? I have a couple of ideas but I'm not fully convinced

**Comment by FelixHenninger** [comment]
(arranged slack meeting for this)

**Comment by rbalet** [comment]
I'll do a new pull request with this issue #60 I'm then closing this one

**Pull request closed without merging**
