### PR TITLE
Transmit plugin: Added retry on failure

### PR DESCRIPTION
**Pull request by jonathon-love**
hi felix,

figured i'd request feedback earlier rather than later.

i'd like to add a little padding between the `Data upload failed` and the retry button, but am not sure what your CSS strategy is here.

also, not really sure how to handle the incremental updates with this either.

cheers

jonathon

### CODE REVIEW

**Comment by jonathon-love** [comment]
so this is failing on:

https://github.com/FelixHenninger/lab.js/blob/master/packages/library/test/plugins.js#L151-L161

because the callback isn't being called. my modifications to `transmit` mean that it won't call that callback *unless* the transmission is successful... (and it can't be successful here because the url is `https://arbitrary.example`).

not sure what you think the correct behaviour should be here.

cheers

**Comment by FelixHenninger** [comment]
Just a quick update: As of 346ef41f748e9a1b3f03b32e304d256c5b5f106c, we automatically retry data transmissions with exponential backoff. This is not entirely what you're looking for, but I hope it's a step in the right direction!

(please note that this is currently deployed only in the beta, not in stable. That's going to change over the coming weeks)

**Comment by FelixHenninger** [comment]
We now (with 6a1c1b788e7837d234494e68eb2fe3e3cca0fce1) automatically include earlier failed transmissions when retransmitting.

Next up: Throttling the number of simultaneous connections (b/c we still swamp slow connections as transmission attempts accumulate over time)

**Comment by FelixHenninger** [comment]
Aaand throttling is done in e838f1ec09d91f27ee4b3090f6f2c80eb9b9ace2

**Comment by jonathon-love** [comment]
haha, so rule `#1` of open source, don't let [potential] contributors lose momentum!

**Comment by FelixHenninger** [comment]
Hej Jonathon, thanks so much for posting!

> don't let [potential] contributors lose momentum!
Point taken, apologies 😔. Would be super-happy to pick this back up if you're interested! 

As with all great contributions, this one hits a hornet's nest of interrelated issues around how to handle the end of the study. I'd be thrilled to discuss this in detail -- you wanna hang in Slack sometime? (the next week is going to be tight b/c of Psychonomics, but maybe we can start a bit slower?)

Cheers, and thanks again for your feedback :-)


-Felix

**Comment by FelixHenninger** [comment]
Ok, so this is done and slated for release soonish, I'ma close this for now. As always, I'm thrilled to discuss things, would love to hear from you!

Thanks for your feedback, and pushing me to improve things :-) -Felix

**Pull request closed without merging**
